### ISSUE TITLE
CRA2 compatibility

### ISSUE THREAD

**Issue by raRaRa** [stereobooster/react-snap#264]
I was just trying out `react-snap` with my project. When I open the site I get a lot of these warnings:

`The resource http://localhost:8000/static/js/5.f6bab7d8.chunk.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriateasvalue and it is preloaded intentionally.`

Are chunks not properly supported, or is this something else?

Thanks!

**Comment by stereobooster** [comment]
I haven't test it with latest CRA2. I only tested it with alpha versions. So yes something can be broken

**Comment by stereobooster** [comment]
Probably connected to https://github.com/facebook/create-react-app/issues/5309

**Comment by raRaRa** [comment]
@stereobooster How will this affect react-snap, that they've started to inline chunks?

**Comment by stereobooster** [comment]
They inline first chunk and this is intentional. We need to investigate further what is broken

**Comment by stereobooster** [comment]
It seems that fix is (package.json):

```js
"reactSnap": {
  "fixWebpackChunksIssue": false
}
```

Please test and tell me if it helps

**Comment by raRaRa** [comment]
@stereobooster Yup sure seems to help! What exactly was the "fix" meant to do, that disabling helps?

**Comment by stereobooster** [comment]
It fixes how webpack chunks are inserted in html in CRA1, it appears they fixed it in CRA2

**Comment by raRaRa** [comment]
Ah sweet! Thanks for the quick solution @stereobooster. Much appreciated!

**Comment by stereobooster** [comment]
Update: `"fixWebpackChunksIssue": false` fixes prerendering, but result has awful Time To First Paint, because it contains script tags in header. CRA2 compatibility needs more work

**Comment by jasan-s** [comment]
Does CRA v2.0.5  fix the issue?

**Comment by stereobooster** [comment]
@jasan-s from my quick tests it seems it works

**Comment by raRaRa** [comment]
Now the big question, inline scripts vs extra requests, with react-snap.

**Comment by tzi** [comment]
If someone here is looking for the solution, the environment variable is `INLINE_RUNTIME_CHUNK`

```
# package.json
{
  "scripts": {
    "build": "INLINE_RUNTIME_CHUNK=false react-scripts build && react-snap"
  }
}
```

Source: https://github.com/facebook/create-react-app/blob/master/docusaurus/docs/advanced-configuration.md

**Comment by uxitten** [comment]
Which is correct? REACT_APP_INLINE_RUNTIME_CHUNK or INLINE_RUNTIME_CHUNK

**Comment by jasan-s** [comment]
@uxitten if you define it in .env file use `REACT_APP_INLINE_RUNTIME_CHUNK` if you add it in the build script use `INLINE_RUNTIME_CHUNK`

**Comment by uxitten** [comment]
@jasan-s thanks, but `TimeoutError` agian
<img width="727" alt="screen shot 2018-11-12 at 12 14 17 pm" src="https://user-images.githubusercontent.com/1549069/48336058-aeea8500-e674-11e8-96b4-f94aa903d756.png">

**Comment by jasan-s** [comment]
did you also add this "fixWebpackChunksIssue": false `react-snap`

**Comment by uxitten** [comment]
yes
this is my dependencies
<img width="293" alt="screen shot 2018-11-12 at 12 16 59 pm" src="https://user-images.githubusercontent.com/1549069/48336165-e822f500-e674-11e8-8949-2828d6401f7f.png">

and react-snap config
<img width="306" alt="screen shot 2018-11-12 at 12 18 07 pm" src="https://user-images.githubusercontent.com/1549069/48336205-07218700-e675-11e8-957d-b74203486bb8.png">

**Comment by stereobooster** [comment]
See this issue for TimeOut https://github.com/stereobooster/react-snap/issues/240

**Comment by stereobooster** [comment]
I finally got to this issue. Try this in `package.json`:

```json
"react-snap": "https://github.com/stereobooster/react-snap.git#crav2",
```
Run `npm i` or `yarn`. Do not use `"fixWebpackChunksIssue": false` or `INLINE_RUNTIME_CHUNK=false`.

**Comment by stereobooster** [comment]
Released fix in v1.22.0

**Comment by kjkta** [comment]
This throws if you have no devDeps.
```
/node_modules/react-snap/run.js:15
  devDependencies["react-scripts"] || dependencies["react-scripts"]
                 ^

TypeError: Cannot read property 'react-scripts' of undefined
```

Fixed in https://github.com/stereobooster/react-snap/pull/312

**Comment by nandorojo** [comment]
Is anyone still experiencing this with `1.23.0`? My client side app won't hydrate.


Server works fine:
![Screen Shot 2020-08-20 at 11 52 53 PM](https://user-images.githubusercontent.com/13172299/90850666-544d8500-e340-11ea-98fd-e1a59d6a91b7.png)

Client doesn't:

![image](https://user-images.githubusercontent.com/13172299/90850679-5dd6ed00-e340-11ea-9706-af13e818fbe3.png)

```tsx
// src/index.tsx
import React from "react";
import "./index.css";
import App from "./App";
import * as serviceWorker from "./serviceWorker";

import { hydrate, render } from "react-dom";

const rootElement = document.getElementById("root");
console.log("hi!!");

if (rootElement && rootElement.hasChildNodes()) {
  hydrate(<App />, rootElement);
} else {
  console.log("[app] render");
  render(<App />, rootElement);
}
// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();
```

I'm running `yarn react-scripts build && yarn react-snap`.
